version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      # Framework gems
      - dependency-name: rake
        dependency-type: direct
      - dependency-name: rspec
        dependency-type: direct
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
