on:
  schedule:
    - cron: '5 12 * * 3'  # 12:05 UTC, Weekly on a Wednesday
  workflow_dispatch:

jobs:
  daniel_the_manual_spaniel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          bundler-cache: true

      - run: bundle exec rake notify:expired
        env:
          REALLY_POST_TO_SLACK: ${{ (github.event_name == 'schedule') && 1 || 0 }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
